#!/bin/sh
# If you are compiling this on OSX make sure to install omp:
#     brew install llvm
#     ln -s /usr/local/opt/llvm/bin/clang++ /usr/local/bin/clang-omp++
#     ln -s /usr/local/opt/llvm/lib/libomp.dylib /usr/local/lib/libomp.dylib
#
# and use this line:
#
#     clang-omp++ -O3 -fopenmp -Wall -std=c++11 -I./src ./demo/ngraph.native.demo/ngraph.native.demo/main.cpp ./src/layout.cpp ./src/quadTree.cpp -o layout++
# If you see an error, make sure xcode is installed (xcode-select --install)

# Otherwise, on Ubuntu, this should work:
g++ -O3 -fopenmp -Wall -std=c++11 -I./src ./demo/gcc/main.cpp ./src/layout.cpp ./src/quadTree.cpp -o layout++
